name: istanbul-metropol-emlak
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22183095128275454
title: 'Kiralık ve satılık: daire, ofis, müstakil ev, villa, residence, arsa'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4874184485524893
  lightness: 0.09036005870439112
  saturation: 0.0957364528439939
  rhythmicContrast: 0.10243507800623775
purpose: []
